[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --production"]

# Skip build phase - using pre-compiled dist
# [phases.build]
# cmds = ["npm run build"]

[start]
cmd = "npm start"